spring.application.name=EcoPortAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/conport
spring.datasource.username=conport
spring.datasource.password=conport

file.upload-dir=/app/uploads/reports

spring.jpa.hibernate.ddl-auto=update