spring.application.name=EcoPortAPI

spring.datasource.url=jbdc:postgresql://localhost:5432/conport
spring.datasource.username=conport
spring.datasource.password=conport

spring.jpa.hibernate.ddl-auto=update