spring.application.name=EcoPortAPI

spring.datasource.url=jdbc:postgresql://localhost:5432/conport
spring.datasource.username=conport
spring.datasource.password=conport

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=120MB

file.upload-dir=/app/uploads/reports

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
